version: 2
jobs:
  publish:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: Setup Rubygems
          command: bash .circleci/setup_rubygems.sh
      - run:
          name: Publish to Rubygems
          command: |
            gem build release_test_nao.gemspec
            gem push "release_test_nao-$(git describe --tags).gem"
workflows:
  version: 2
  deploy:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v[0-9](\.[0-9]){2}$/
            branches:
              ignore: /.*/